#pragma once

template <class T>
class CProxy_IWebRTCAVControlEvents : public IConnectionPointImpl<T, &__uuidof(_IWebRTCAVControlEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
